// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TAdmin
{
    public int FEmployeeId { get; set; }

    public string FEmployeeName { get; set; }

    public string FEmployeeEmail { get; set; }

    public string FPassword { get; set; }

    public string FAdminRole { get; set; }

    public DateTime? FAdminJoinDate { get; set; }

    public bool? FAccountStatus { get; set; }

    public string FNote { get; set; }

    public virtual ICollection<TPushMessage> TPushMessages { get; set; } = new List<TPushMessage>();

    public virtual ICollection<TServiceForm> TServiceForms { get; set; } = new List<TServiceForm>();
}