// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TChatRoomTeacher
{
    public int ChatRoomId { get; set; }

    public int FMemberId { get; set; }

    public int FTeacherId { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TTeacher FTeacher { get; set; }

    public virtual ICollection<TChatMessageTeacher> TChatMessageTeachers { get; set; } = new List<TChatMessageTeacher>();
}