// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCity
{
    public int FCityId { get; set; }

    public string FCityName { get; set; }

    public virtual ICollection<TCityDistrict> TCityDistricts { get; set; } = new List<TCityDistrict>();

    public virtual ICollection<TMemberCitiesList> TMemberCitiesLists { get; set; } = new List<TMemberCitiesList>();
}