// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCityDistrict
{
    public int FDistrictId { get; set; }

    public string FDistrictName { get; set; }

    public int FCityId { get; set; }

    public virtual TCity FCity { get; set; }

    public virtual ICollection<TLessonCourse> TLessonCourses { get; set; } = new List<TLessonCourse>();
}