// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCourseworkFile
{
    public int FCourseworkFileId { get; set; }

    public int FCourseworkId { get; set; }

    public string FFileName { get; set; }

    public string FFileFormat { get; set; }

    public string FFileLink { get; set; }

    public int FFileSize { get; set; }

    public virtual TCoursework FCoursework { get; set; }
}