// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCourseSubject
{
    public int FFieldId { get; set; }

    public int FSubjectId { get; set; }

    public string FSubjectName { get; set; }

    public string FSubjectCode { get; set; }

    public virtual TCourseField FField { get; set; }

    public virtual ICollection<TLessonCourse> TLessonCourses { get; set; } = new List<TLessonCourse>();

    public virtual ICollection<TTeacherSubject> TTeacherSubjects { get; set; } = new List<TTeacherSubject>();
}