// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCouponConditionList
{
    public int FCouponConditionId { get; set; }

    public string FCouponConditionName { get; set; }

    public int? FTeacherId { get; set; }

    public bool? FCourseType { get; set; }

    public int? FFieldId { get; set; }

    public int? FSubjectId { get; set; }

    public bool FNewRegistrantOrNot { get; set; }

    public short? FBirthdayOffer { get; set; }

    public virtual ICollection<TCoupon> TCoupons { get; set; } = new List<TCoupon>();
}