// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCourseField
{
    public int FFieldId { get; set; }

    public string FFieldName { get; set; }

    public string FFieldCode { get; set; }

    public virtual ICollection<TCourseSubject> TCourseSubjects { get; set; } = new List<TCourseSubject>();

    public virtual ICollection<TMemberWishField> TMemberWishFields { get; set; } = new List<TMemberWishField>();
}