// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCoursework
{
    public int FCourseworkId { get; set; }

    public int FOrderDetailId { get; set; }

    public string FName { get; set; }

    public string FDescrpition { get; set; }

    public DateTime FLastModifyTime { get; set; }

    public int? FMemberId { get; set; }

    public string FShareAudience { get; set; }

    public string FComment { get; set; }
    public string FCommentPerson { get; set; }

    public DateTime? FCommentTime { get; set; }

    public virtual TOrderDetail FOrderDetail { get; set; }

    public virtual ICollection<TCourseworkFile> TCourseworkFiles { get; set; } = new List<TCourseworkFile>();
}