// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TCoupon
{
    public int FCouponId { get; set; }

    public string FDiscountCode { get; set; }

    public bool FCouponValidOrNot { get; set; }

    public decimal FCouponDiscount { get; set; }

    public DateTime FCouponCreatedDate { get; set; }

    public DateTime FCouponStartDate { get; set; }

    public DateTime FCouponEndDate { get; set; }

    public int? FCouponConditionId { get; set; }

    public virtual TCouponConditionList FCouponCondition { get; set; }
}