// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TLessonEvaluation
{
    public int FLessonEvalId { get; set; }

    public int FMemberId { get; set; }

    public int FOrderDetailId { get; set; }

    public int FScore { get; set; }

    public string FComment { get; set; }

    public DateTime FCommentDate { get; set; }

    public DateTime? FCommentUpdateDate { get; set; }

    public bool FDisplayStatus { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TOrderDetail FOrderDetail { get; set; }
}