// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TMemberWishField
{
    public int FMwishFieldsId { get; set; }

    public int FMemberId { get; set; }

    public int FFieldId { get; set; }

    public virtual TCourseField FField { get; set; }

    public virtual TMember FMember { get; set; }
}