// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TMemberCitiesList
{
    public int FMcitiesId { get; set; }

    public int FMemberId { get; set; }

    public int FCityId { get; set; }

    public virtual TCity FCity { get; set; }

    public virtual TMember FMember { get; set; }
}