// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TMemberGetPush
{
    public int FMemberGetPushId { get; set; }

    public int FMemberId { get; set; }

    public int FPushMessageId { get; set; }

    public bool? FPushRead { get; set; }

    public DateTime FPushCreatedTime { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TPushMessage FPushMessage { get; set; }
}