// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TMemberFavCourse
{
    public int FMfavCid { get; set; }

    public int FMemberId { get; set; }

    public int FLessonCourseId { get; set; }

    public virtual TLessonCourse FLessonCourse { get; set; }

    public virtual TMember FMember { get; set; }
}