// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TMemberFavTeacher
{
    public int FMfavTid { get; set; }

    public int FMemberId { get; set; }

    public int FTeacherId { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TTeacher FTeacher { get; set; }
}