// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TOrder
{
    public int FOrderId { get; set; }

    public int FMemberId { get; set; }

    public DateTime FOrderDate { get; set; }

    public int? FCouponId { get; set; }

    public string FPaymentMethod { get; set; }

    public string FOrderNumber { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual ICollection<TOrderDetail> TOrderDetails { get; set; } = new List<TOrderDetail>();
}