// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TOrderDetail
{
    public int FOrderId { get; set; }

    public int FOrderDetailId { get; set; }

    public int FLessonCourseId { get; set; }

    public decimal FLessonPrice { get; set; }

    public decimal? FDiscount { get; set; }

    public bool FOrderValid { get; set; }

    public string FModificationDescription { get; set; }

    public virtual TLessonCourse FLessonCourse { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual ICollection<TCoursework> TCourseworks { get; set; } = new List<TCoursework>();

    public virtual ICollection<TLessonEvaluation> TLessonEvaluations { get; set; } = new List<TLessonEvaluation>();
}