// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TPushMessage
{
    public int FPushMessageId { get; set; }

    public string FPushType { get; set; }

    public int FPushLayoutId { get; set; }

    public string FPushMethod { get; set; }

    public DateTime FPushStartDate { get; set; }

    public DateTime FPushEndDate { get; set; }

    public string FPushContent { get; set; }

    public byte[] FPushImagePath { get; set; }

    public DateTime FPushCreatedTime { get; set; }

    public DateTime FPushLastUpdatedTime { get; set; }

    public int FEmployeeId { get; set; }

    public virtual TAdmin FEmployee { get; set; }

    public virtual TPushLayout FPushLayout { get; set; }

    public virtual ICollection<TMemberGetPush> TMemberGetPushes { get; set; } = new List<TMemberGetPush>();
}