// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TPushLayout
{
    public int FPushLayoutId { get; set; }

    public string FLayoutName { get; set; }

    public virtual ICollection<TPushMessage> TPushMessages { get; set; } = new List<TPushMessage>();
}