// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TServiceForm
{
    public int FServiceId { get; set; }

    public int FMemberId { get; set; }

    public int? FEmployeeId { get; set; }

    public int? FServiceParentId { get; set; }

    public DateTime FServiceCreatedTime { get; set; }

    public string FServiceChannel { get; set; }

    public string FServiceType { get; set; }

    public string FServiceTag { get; set; }

    public string FServiceContent { get; set; }

    public DateTime? FServiceClosedTime { get; set; }

    public string FServiceStatus { get; set; }

    public int? FServiceStep { get; set; }

    public string FServiceFormType { get; set; }

    public virtual TAdmin FEmployee { get; set; }
}