// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TTeacher
{
    public int FMemberId { get; set; }

    public int FTeacherId { get; set; }

    public string FTeacherName { get; set; }

    public DateTime FJoinDatetime { get; set; }

    public byte[] FTeacherProfilePic { get; set; }

    public string FIntroduction { get; set; }

    public string FContactInfo { get; set; }

    public string FNote { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual ICollection<TChatMessageTeacher> TChatMessageTeachers { get; set; } = new List<TChatMessageTeacher>();

    public virtual ICollection<TChatRoomTeacher> TChatRoomTeachers { get; set; } = new List<TChatRoomTeacher>();

    public virtual ICollection<TLessonCourse> TLessonCourses { get; set; } = new List<TLessonCourse>();

    public virtual ICollection<TMemberFavTeacher> TMemberFavTeachers { get; set; } = new List<TMemberFavTeacher>();

    public virtual ICollection<TTeacherImage> TTeacherImages { get; set; } = new List<TTeacherImage>();

    public virtual ICollection<TTeacherSubject> TTeacherSubjects { get; set; } = new List<TTeacherSubject>();

    public virtual ICollection<TVideoUploadUrl> TVideoUploadUrls { get; set; } = new List<TVideoUploadUrl>();
}