// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TTeacherApplyLog
{
    public int FApplyLogId { get; set; }

    public DateTime FApplyDatetime { get; set; }

    public int FMemberId { get; set; }

    public string FTeacherName { get; set; }

    public string FRealName { get; set; }

    public string FContactInfo { get; set; }

    public string FIntroduction { get; set; }

    public string FReason { get; set; }

    public string FPdfLink { get; set; }

    public string FTeacherPlanLink { get; set; }

    public string FProgressStatus { get; set; }

    public bool? FReviewResult { get; set; }

    public DateTime? FReviewDatetime { get; set; }

    public int? FEmployeeId { get; set; }

    public string FNote { get; set; }

    public virtual TMember FMember { get; set; }
}