// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TVenueProviderInfo
{
    public int FVenueProviderId { get; set; }

    public string FName { get; set; }

    public string FGuinumber { get; set; }

    public string FPassword { get; set; }

    public string FContactName { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public virtual ICollection<TVenue> TVenues { get; set; } = new List<TVenue>();
}