// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TVideoCourse
{
    public int FVideoCourseId { get; set; }

    public int FSubjectId { get; set; }

    public string FCode { get; set; }

    public int FTeacherId { get; set; }

    public string FName { get; set; }

    public string FDescription { get; set; }

    public string FRequirement { get; set; }

    public byte[] FCoursePhoto { get; set; }

    public decimal? FPrice { get; set; }

    public string FHomeworkDescription { get; set; }

    public string FValidate { get; set; }

    public bool FLaunchStatus { get; set; }

    public DateTime? FUploadDate { get; set; }

    public string FNote { get; set; }

    public DateTime? FUpdateDate { get; set; }
}