// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TVideoUploadUrl
{
    public int FVideoUploadUrlId { get; set; }

    public int FTeacherId { get; set; }

    public string FVideoName { get; set; }

    public string FVideoPath { get; set; }

    public DateTime? FUploadTime { get; set; }

    public virtual TTeacher FTeacher { get; set; }
}