// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TVideoCourseQa
{
    public int FVideoCourseQaid { get; set; }

    public int FVideoCourseId { get; set; }

    public int FMemberId { get; set; }

    public string FPurpose { get; set; }

    public string FQuestion { get; set; }

    public DateTime FQuestionDate { get; set; }

    public string FAnswer { get; set; }

    public DateTime? FAnswerDate { get; set; }

    public bool FAnswerCondition { get; set; }

    public bool FDisplayStatus { get; set; }
}