// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models;

public partial class TVideoCourseEvaluation
{
    public int FVideoCourseEvalId { get; set; }

    public int FMemberId { get; set; }

    public int FVideoCourseId { get; set; }

    public int FScore { get; set; }

    public string FComment { get; set; }

    public DateTime FCommentDate { get; set; }

    public DateTime? FCommentUpdateDate { get; set; }

    public bool FDisplayStatus { get; set; }
}