// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalGroupMVCPrj.Models.DTO
{
public class ChatRoomInfoDTO
    {
        public int UserId { get; set; }
        public TChatMessageDTO LastMessage { get; set; }
        public int UnreadMessagesCount { get; set; }
    }
}